# -*- coding: utf-8 -*-
"""helper1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLG2MmVMK9yC9knDOiGzQJ31izEEx6DY
"""

import requests
import os

def download_csv(url, save_path):
    """
    Downloads a CSV file from the given URL and saves it to the specified path.

    Parameters:
    - url (str): The URL of the CSV file.
    - save_path (str): The local path (including filename) where the file should be saved.

    Returns:
    - str: The file path if the download was successful.
    """
    try:
        # Send a GET request to the URL
        response = requests.get(url, stream=True)
        response.raise_for_status()  # Raise an error for HTTP errors

        # Check if the directory exists, create if not
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

        # Write the content to the file
        with open(save_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=1024):  # Download in chunks
                file.write(chunk)

        print(f"File successfully downloaded and saved to {save_path}")
        return save_path
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None
    except IOError as io_error:
        print(f"File write error: {io_error}")
        return None